### ISSUE TITLE
Tag editor

### ISSUE THREAD

**Issue by davelab6** [katydecorah/font-library#35]
The instructions in https://github.com/katydecorah/font-library#contributing require web development skills ("json commas missing, argh!&^%$") 

I'd like to propose tag editor functionality, using the Github API (similar to www.prose.io)
1. Click the 'contribute' button at the top, same as today
2. see a modal with which to log into github (https://developer.github.com/v3/oauth_authorizations/#get-or-create-an-authorization-for-a-specific-app)
3. display https://raw.githubusercontent.com/katydecorah/font-library/gh-pages/families.json as a simple table with 2 cols, the families in col 1, and the tags list as a single comma separated string in col 2, where each cell in the col body is an editable 'text' form element (`<inputtype="text" name="$family-tags">`), Or, something better, designed in harmony with the current UI :)
4. display a progress bar somewhere, showing the progress of checking if the $user/font-library repo exists (https://developer.github.com/v3/repos/#list-your-repositories) 
5. and if not, cloning https://github.com/katydecorah/font-library into the user's account (https://developer.github.com/v3/repos/forks/#create-a-fork)
6. somewhere have a `<submit />` button, that makes a markdown unordered list of the families that are updated, converts the form data back into the JSON format
7. branch the repo (https://gist.github.com/potherca/3964930)
8. commit the JSON to that branch (https://developer.github.com/v3/repos/contents/#update-a-file)
9. make a pull request to https://github.com/katydecorah/font-library with the md list as the pull request text (https://developer.github.com/v3/pulls/#create-a-pull-request)

**Comment by katydecorah** [comment]
I have pondered something similar to make editing tags faster and easier. However, I do have some pause. The main reason I prefer not to have a GUI editor is because it removes the possiblity of someone to make their first PR. While I agree that a GUI is more accessible, we take away the experience of contributing. (And this was one of the main reasons I wanted to make this project open source.) 

I would prefer to write more meaningful contributing docs and having more power contributors offer themselves as mentors than to build a system that does it for them.

Another thing about form-styled submissions is that making the process too easy can result is low-quality submissions or even spam. Having to create a PR and go through the processes adds just enough friction.

Also just noting that right now there is a [simple test to lint the JSON file](https://github.com/katydecorah/font-library/blob/gh-pages/Rakefile#L12), so the PR will fail if there are missing commas, etc. I'm definitely in favor of building out more robust tests!
